from handlers.handle import *
urlList = [
    (r"/", MainHandler),
    # (r"/logout", MainHandler),
    (r"/about", AboutHandler),
    (r"/latest", LatestHandler),
    (r"/legal", LegalHandler),
    (r"/copyright", CopyrightHandler),
    (r"/privacy", PrivacyHandler),
    (r"/contact", ContactHandler),
    (r"/whetting", WhettingHandler),
    (r"/interpreter", InterpreterHandler),
    (r"/intro", IntroHandler),
    (r"/control_flow", ControlFlowHandler),
    (r"/send_info", ContactHandler),
    (r"/login", LoginHandler),
    (r"/comment", CommentsHandler),
    (r"/password", ModifyPassword),
    (r"/postedit", PostEditHandler),
    (r"/compose", ComposeHandler),
    (r"/ds", DSHandler),
    (r"/modules", ModulesHandler),
    (r"/io", IOHandler),
    (r"/error", ErrorHander),
    (r"/classes", ClassesHandler),
]
